In [1]:
%cd ..

/data/projects/tcrio/tcrio

In [2]:
import polars as pl

In [3]:
df = pl.DataFrame({"name": ["Alice", "Bob", "Charlie"], "age": [25, 30, 35], "days_since_birth": [-9125, -10950, -12775], "favourite_adverb": ["quickly", "slowly", "happily"]})

In [5]:
from triassic.constants.junction import analyze_junctions

In [6]:
df.with_columns(
    snowball_stem("favourite_adverb").alias("favourite_adverb_stemmed"),
    noop("age").alias("age_noop"),
    abs_numeric("days_since_birth").alias("days_since_birth_abs"),
    add_suffix("name", suffix="tytonky").alias("name_with_suffix"),
)

shape: (3, 8)
┌─────────┬─────┬──────────────┬──────────────┬─────────────┬──────────┬─────────────┬─────────────┐
│ name    ┆ age ┆ days_since_b ┆ favourite_ad ┆ favourite_a ┆ age_noop ┆ days_since_ ┆ name_with_s │
│ ---     ┆ --- ┆ irth         ┆ verb         ┆ dverb_stemm ┆ ---      ┆ birth_abs   ┆ uffix       │
│ str     ┆ i64 ┆ ---          ┆ ---          ┆ ed          ┆ i64      ┆ ---         ┆ ---         │
│         ┆     ┆ i64          ┆ str          ┆ ---         ┆          ┆ i64         ┆ str         │
│         ┆     ┆              ┆              ┆ str         ┆          ┆             ┆             │
╞═════════╪═════╪══════════════╪══════════════╪═════════════╪══════════╪═════════════╪═════════════╡
│ Alice   ┆ 25  ┆ -9125        ┆ quickly      ┆ quick       ┆ 25       ┆ 9125        ┆ Alicetytonk │
│         ┆     ┆              ┆              ┆             ┆          ┆             ┆ y           │
│ Bob     ┆ 30  ┆ -10950       ┆ slowly       ┆ slowli      ┆ 30       ┆ 10950       ┆ Bobtytonky  │
│ Charlie ┆ 35  ┆ -12775       ┆ happily      ┆ happili     ┆ 35       ┆ 12775       ┆ Charlietyto │
│         ┆     ┆              ┆              ┆             ┆          ┆             ┆ nky         │
└─────────┴─────┴──────────────┴──────────────┴─────────────┴──────────┴─────────────┴─────────────┘

In [ ]:
df.with_columns(
    snowball_stem("favourite_adverb").alias("favourite_adverb_stemmed"),
    noop("age").alias("age_noop"),
    abs_numeric("days_since_birth").alias("days_since_birth_abs"),
    add_suffix("name", suffix="tytonky").alias("name_with_suffix"),
)

shape: (3, 8)
┌─────────┬─────┬──────────────┬──────────────┬─────────────┬──────────┬─────────────┬─────────────┐
│ name    ┆ age ┆ days_since_b ┆ favourite_ad ┆ favourite_a ┆ age_noop ┆ days_since_ ┆ name_with_s │
│ ---     ┆ --- ┆ irth         ┆ verb         ┆ dverb_stemm ┆ ---      ┆ birth_abs   ┆ uffix       │
│ str     ┆ i64 ┆ ---          ┆ ---          ┆ ed          ┆ i64      ┆ ---         ┆ ---         │
│         ┆     ┆ i64          ┆ str          ┆ ---         ┆          ┆ i64         ┆ str         │
│         ┆     ┆              ┆              ┆ str         ┆          ┆             ┆             │
╞═════════╪═════╪══════════════╪══════════════╪═════════════╪══════════╪═════════════╪═════════════╡
│ Alice   ┆ 25  ┆ -9125        ┆ quickly      ┆ quick       ┆ 25       ┆ 9125        ┆ Alicetytonk │
│         ┆     ┆              ┆              ┆             ┆          ┆             ┆ y           │
│ Bob     ┆ 30  ┆ -10950       ┆ slowly       ┆ slowli      ┆ 30       ┆ 10950       ┆ Bobtytonky  │
│ Charlie ┆ 35  ┆ -12775       ┆ happily      ┆ happili     ┆ 35       ┆ 12775       ┆ Charlietyto │
│         ┆     ┆              ┆              ┆             ┆          ┆             ┆ nky         │
└─────────┴─────┴──────────────┴──────────────┴─────────────┴──────────┴─────────────┴─────────────┘